### ISSUE TITLE
Example how to use with --path

### ISSUE THREAD

**Issue by Thibescobar** [dicomsort/dicomsorter#5]
Hello, 

First of all thank you for the tool ! It seems to be very usefull. Unfortunately I have difficulties to install DICOM sort. 
On MACOS (Mojave 10.14.6), I downloaded the .dmg and extract the .app in the Applications folder but when I double click on the app, nothing happen... 
On Linux (CentOS 7), I have difficulties to install from source (I will continue to try, but if you have advices it could be helpful). 

Because of these difficulties, I tried to use the python lib dicomsorter instead of the GUI app... The lib works well, but I do not really understand how to use `--path` . I have this error : 

```
(base) macbook-air-de-thibault:~ thibaultescobar$ conda activate SORT27
(SORT27) macbook-air-de-thibault:~ thibaultescobar$ python --version
Python 2.7.17 :: Anaconda, Inc.
(SORT27) macbook-air-de-thibault:~ thibaultescobar$ dicomsorter --path [PatiendID] /Users/thibaultescobar/Downloads/DICOMvrac /Users/thibaultescobar/Downloads/DICOMsorted
usage: dicomsorter [-h] [--version] [--path PATH [PATH ...]]
                   [--filename-format FILENAME_FORMAT] [--anonymize]
                   [--overwrite] [--list-fields] [--verbose] [--dry-run]
                   [--original-filename] [--concurrency CONCURRENCY] [--move]
                   [--force]
                   input_directory output_directory
dicomsorter: error: too few arguments
(SORT27) macbook-air-de-thibault:~ thibaultescobar$ 
```
Can you just give me an example please ? 

If you have an idea on how can I use the GUI version it would be even greater. 

PS : I work in conda environments

Thanks again !
Have a good day !

**Comment by suever** [comment]
That is odd that you cannot get the binary to run on Mojave. I can try later and see if I can reproduce the issue. Do you mind filing an issue in the other repository about that so I can look into it there?

With respect to the command-line version in this repo, you want to omit the square brackets which I think may be causing your issue:

```
dicomsorter --path PatientID /Users/thibaultescobar/Downloads/DICOMvrac /Users/thibaultescobar/Downloads/DICOMsorted
```

Let me know if that works for you

**Comment by Thibescobar** [comment]
Thank you for you answer, I will open the issus about the GUI app in the good place. 

About the the command line version, I tried but still have the same problem: 
```
(base) macbook-air-de-thibault:~ thibaultescobar$ conda activate SORT27
(SORT27) macbook-air-de-thibault:~ thibaultescobar$ dicomsorter --path PatientID /Users/thibaultescobar/Downloads/DICOMvrac /Users/thibaultescobar/Downloads/DICOMsorted
usage: dicomsorter [-h] [--version] [--path PATH [PATH ...]]
                   [--filename-format FILENAME_FORMAT] [--anonymize]
                   [--overwrite] [--list-fields] [--verbose] [--dry-run]
                   [--original-filename] [--concurrency CONCURRENCY] [--move]
                   [--force]
                   input_directory output_directory
dicomsorter: error: too few arguments
(SORT27) macbook-air-de-thibault:~ thibaultescobar$ 
```

Do you thinks the conda environment can have a link with this issue ?

**Comment by suever** [comment]
@Thibescobar Ok so I figured out what the issue is. `argparse` (which I'm using for command line parsing) does not like having a flag that can take many values: `--path PatientID SeriesNumber` to be before the positional arguments (`input_directory` and `output_directory`) although the help text that is automatically provided by `argparse` shows the positional arguments at the end. Weird.

To get around this, you can put the positional arguments first:

```
dicomsorter /Users/thibaultescobar/Downloads/DICOMvrac /Users/thibaultescobar/Downloads/DICOMsorted --path PatientID SeriesDescription
```

Does that work for you?

**Comment by Thibescobar** [comment]
Yes that work ! 
Thank you very much
